lower batch limit
osmlab/maproulette-java-client pull request #82
Opened 2022-04-12 22:32 UTC by jschwarz2030

### Description:

Lower batch limit of tasks allowed in a challenge task batch upload

### Unit Test Approach:

Re-ran batchTest

### Test Results:

batchTest succeeds

------

In doubt: [Contributing Guidelines](../CONTRIBUTING.md)

2022-04-15 18:32 UTC, ljdelight requested changes

2022-04-15 18:32 UTC, ljdelight commented on src/integrationTest/java/org/maproulette/client/batch/BatchUploaderIntegrationTest.java
> +    private static final int NUMBER_TASKS = 30000;
I don't think we should change this since GH action machines are limited by CPU/RAM (it would likely fail the build, it fails on my beefy desktop) and we want integration tests to be pretty quick.

If you wanted the integration tests to go through the code path where max count will cause a flush, `IntegrationBase.getConfiguration` can be modified to set the batch size with `this.configuration.setBatchSize(5)`. There are other ways but that makes it so that all integration tests use a low batch size.

2022-04-18 16:19 UTC, mgcuthbert approved these changes

2022-04-18 16:31 UTC, ljdelight approved these changes

2022-04-18 16:42 UTC, merged